version: '3'

services:
  node-app:
    build: .
    image: node-app
    ports:
      - '3000:3000'
    depends_on:
      - postgresdb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network
  
  postgresdb:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=notemed
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - node-network

volumes:
  db:

networks:
  node-network:
    driver: bridge
